### ISSUE TITLE
AttributeError: 'attack_msf' object has no attribute 'cone_f' when running baseline.py

### ISSUE THREAD

**Issue by ElaineYao** [ASGuard-UCI/MSF-ADV#5]
Thanks for sharing the artifact from your IEEE S&P work.

I got the following issue: `AttributeError: 'attack_msf' object has no attribute 'cone_f'` when running /evaluation/baseline.py [Line 233](https://github.com/ASGuard-UCI/MSF-ADV/blob/master/evaluation/baseline.py#L233)
I assume that `self.cone_f` should be have been defined in the code but now it's missing.

What value should I assign to self.cone_f? 

Thanks

**Comment by anhtu96** [comment]
> 

Hi, I'm also facing this issue. This line of code is in rendering_img function, which is similar to the same one in attack.py. Inspecting more inside the function from attack.py I observe this render.render(self.ray_direction, self.length, self.object_v, self.object_f, self.i_final), and the one from baseline.py is render.render(ray_direction, length, vertex, face, i_final). So my guessing here is that self.cone_f should be self.object_f.

**Comment by ElaineYao** [comment]
It makes sense! Thank you, it works! @anhtu96

**Comment by yuefeizaishi** [comment]
Hello, did your baseline. py code run successfully? When the code runs to "result=differential_ When evolution (obj. rendering_img, bound, maxiter=1000, popsize=3, workers=1, disp=True, updating='deferred ') "falls into a dead loop，I tried to modify the bounds and maxiter parameters, but it still didn't work.
